function writeHyperstack(filenamepath, I)
    fiji_descr = ['ImageJ=1.53c' newline ...
        'images=' num2str(size(I,4)*...
        size(I,3)*...
        size(I,5)) newline...
        'channels=' num2str(size(I,4)) newline...
        'slices=' num2str(size(I,3)) newline...
        'frames=' num2str(size(I,5)) newline...
        'hyperstack=true' newline...
        'mode=grayscale' newline...
        'loop=false' newline...
        'min=0.0' newline...
        'max=65535.0'];  % change this to 256 if you use an 8bit image

    t = Tiff(char(filenamepath),'w');
    tagstruct.ImageLength = size(I,1);
    tagstruct.ImageWidth = size(I,2);
    tagstruct.Photometric = Tiff.Photometric.MinIsBlack;
    tagstruct.BitsPerSample = 16;
    tagstruct.SamplesPerPixel = 1;
    tagstruct.Compression = Tiff.Compression.LZW;
    tagstruct.PlanarConfiguration = Tiff.PlanarConfiguration.Chunky;
    tagstruct.SampleFormat = Tiff.SampleFormat.UInt;
    tagstruct.ImageDescription = fiji_descr;
    for frame = 1:size(I,5)
        for slice = 1:size(I,3)
            for channel = 1:size(I,4)
                t.setTag(tagstruct)
                t.write(im2uint16(I(:,:,slice,channel,frame)));
                t.writeDirectory(); % saves a new page in the tiff file
            end
        end
    end
    t.close()
end